version: "3"
services:
  receipt-processor-service:
    env_file:
      - .env
    container_name: receipt-processor-service
    network_mode: "bridge"
    build: .
    command: npm run start
    ports:
      - "7070:7070"
    volumes:
      - "./:/usr/src/app"
      - /usr/src/app/node_modules